# Site settings
title: Burusothman Ahiladas 
description: CV
favicon: /assets/img/favicon.icon
baseurl: https://brusoth09.github.io/
url: https://brusoth09.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1
cv-path: /assets/docs/Burusoth_Ahiladas.pdf

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Burusothman Ahiladas
  title: Software Engineer
  address: Colombo, Sri Lanaka
  email: brusoth09@gmail.com
  link: 
  weibo:
  github: brusoth09
  linkedin: burusoth
  twitter: brusoth09
  gavatar: /assets/img/burusoth.jpg
  stackoverflow: 2798955
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Zone24x7 (Pvt) Ltd.
      location: Colombo, Sri Lanka
      title: Software Engineer
      started: 2015
      duration: (April 2015 - Present)
      description: Zone24x7 is one of the technology solution company which provides hardware and software solutions.
    - work2:
      company: University of Moratuwa
      location: Colombo, Sri Lanka
      title: Visiting Instructor
      started: 2014
      duration: (November 2014 - April 2015)
      description: Worked as Instructor to teach Programming Fundamentals and Python Language.
    - work3:
      company: University of Moratuwa
      location: Colombo, Sri Lanka
      title: Research and Development Project Engineer
      started: 2014
      duration: (May 2014 - February 2015)
      description: I have done my final year reserach and development project here.
    - work4:
      company: University of Moratuwa
      location: Colombo, Sri Lanka
      title: Associate Software Engineer
      started: 2013
      duration: (November 2013 - April 2014)
      description: Add Here!
    - work4:
      company: ATUTS (Pvt) Ltd.
      location: Colombo, Sri Lanka
      title: Trainee Software Engineer
      started: 2012
      duration: (November 2012 - October 2013)
      description: ATUTS is a start-up company with about 10 employess. I started my career there as a Trainee Software Engineer. Here I worked in two projects. First one is a Web Application called FundtheNeedy. We used Spring Framework, JSP, Hibernate, MySQL in this project.
  educationHistory:
    - education1:
      organization: University of Moratuwa
      location: Moratuwa, Sri Lanka
      degree: Bachelor
      major: BSc. (Hons) Computer Science and Engineering
      started: 2010
      duration: (2010 - 2015)
      description: Completed by Bachelor degree with second lower class. And had my convocation on 17th September 2015 at the Bandaranaike Memorial International Conference Hall
    - education1:
      organization: Jaffna Hindu College
      location: Jaffna, Sri Lanka
      degree: 3 Higer Distinction
      major: Advance Level Examination
      started: 2009
      duration: (2006 - 2009)
      description: Got 3A in Mathematics Stream with island rank of 70. And got Mahapola Higher Education (Super Merit) Scholarship Ministry of Higher Education, Sri Lanka 2010
  languages:
    - language1:
      name: Tamil
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Sinhala
      proficiency: Limit
  programmingSkills:
    - category1:
      name: Programming
      skills:
        - skill1:
          name: Java
        - skill2:
          name: C
        - skill3:
          name: PHP
        - skill4:
          name: C#
        - skill5:
          name: Shell Script
        - skill6:
          name: Scala
    - category2:
      name: Web Development
      skills:
        - skill1:
          name: J2EE
        - skill2:
          name: JSP
        - skill3:
          name: Servlets
        - skill4:
          name: CSS
        - skill5:
          name: Java Script
        - skill6:
          name: JQuery
    - category3:
      name: Big Data
      skills:
        - skill1:
          name: Hadoop
        - skill2:
          name: HBase
        - skill3:
          name: Hive
        - skill4:
          name: Pig
        - skill5:
          name: Elastic Search
        - skill6:
          name: AWS
    - category4:
      name: Databases & ORM
      skills:
        - skill1:
          name: HBase
        - skill2:
          name: MongoDB
        - skill3:
          name: MySQL
        - skill4:
          name: Oracle Database
        - skill5:
          name: Hibernate
        - skill6:
          name: Doctrine
    - category5:
      name: Frame Works
      skills:
        - skill1:
          name: Spring
        - skill2:
          name: Play
        - skill3:
          name: Struts 2
        - skill4:
          name: Symfony 2
    - category6:
      name: Analysis
      skills:
        - skill1:
          name: Natural Language Processing
        - skill2:
          name: Sentiment analysis
        - skill3:
          name: Data Mining
        - skill4:
          name: Machine Learning
    - category7:
      name: IDE and Tools
      skills:
        - skill1:
          name: TDD
        - skill2:
          name: JUnit
        - skill3:
          name: TestNG
        - skill4:
          name: Mockito
    - category8:
      name: Application Servers
      skills:
        - skill1:
          name: Tomcat
        - skill2:
          name: Jetty
        - skill3:
          name: JBoss





