# Site settings
title: Burusothman Ahiladas 
description: CV
favicon: /assets/img/burusoth.jpg
baseurl: https://brusoth09.github.io/
url: https://brusoth09.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Burusothman Ahiladas
  title: Software Engineer
  address: Colombo, Sri Lanaka
  email: brusoth09@gmail.com
  link: 
  weibo:
  github: brusoth09
  linkedin: https://lk.linkedin.com/in/burusoth
  twitter: brusoth09
  gavatar: /assets/img/burusoth.jpg
  stackoverflow: 2798955
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Zone24x7 (Pvt) Ltd.
      location: Colombo, Sri Lanka
      title: Software Engineer
      started: 2015
      duration: (April 2015 - Present)
      description: Zone24x7 is one of the technology solution company which provides hardware and software solutions.
    - work2:
      company: University of Moratuwa
      location: Colombo, Sri Lanka
      title: Visiting Instructor
      started: 2014
      duration: (November 2014 - April 2015)
      description: Worked as Instructor for python module.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Northeastern University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Tamil
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Sinhala
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
