# Site settings
title: Burusothman Ahiladas 
description: CV
favicon: /assets/img/burusoth.jpg
baseurl: https://brusoth09.github.io/
url: https://brusoth09.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1
cv-path: /assets/docs/Burusoth_Ahiladas.pdf

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Burusothman Ahiladas
  title: Software Engineer
  address: Colombo, Sri Lanaka
  email: brusoth09@gmail.com
  link: 
  weibo:
  github: brusoth09
  linkedin: burusoth
  twitter: brusoth09
  gavatar: /assets/img/burusoth.jpg
  stackoverflow: 2798955
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Zone24x7 (Pvt) Ltd.
      location: Colombo, Sri Lanka
      title: Software Engineer
      started: 2015
      duration: (April 2015 - Present)
      description: Zone24x7 is one of the technology solution company which provides hardware and software solutions.
    - work2:
      company: University of Moratuwa
      location: Colombo, Sri Lanka
      title: Visiting Instructor
      started: 2014
      duration: (November 2014 - April 2015)
      description: Worked as Instructor for python module.
    - work3:
      company: University of Moratuwa
      location: Colombo, Sri Lanka
      title: Research and Development Project Engineer
      started: 2014
      duration: (May 2014 - February 2015)
      description: I have done my final year reserach and development project here.
    - work4:
      company: University of Moratuwa
      location: Colombo, Sri Lanka
      title: Associate Software Engineer
      started: 2013
      duration: (November 2013 - April 2014)
      description: Add Here!
    - work4:
      company: ATUTS (Pvt) Ltd.
      location: Colombo, Sri Lanka
      title: Trainee Software Engineer
      started: 2012
      duration: (November 2012 - October 2013)
      description: Add Here!
  educationHistory:
    - education1: BSc. (Hons) Computer Science and Engineering
      organization: University of Moratuwa
      location: Moratuwa, Sri Lanka
      degree: Bachelor
      major: Associate Software Engineer
      started: 2010
      duration: (2010 - 2015)
      description: Add here!
  languages:
    - language1:
      name: Tamil
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Sinhala
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
